FROM resin/%%RESIN_MACHINE_NAME%%-node

ENV INITSYSTEM on

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app

WORKDIR /
RUN sudo apt-get update
RUN sudo apt-get install -t wheezy i2c-tools


EXPOSE 8080
CMD [ "npm", "start" ]
