FROM resin/%%RESIN_MACHINE_NAME%%-node

ENV INITSYSTEM on
# 
# COPY package.json /package.json
# RUN npm install
#
# COPY src/ /usr/src/app
# CMD ["node", "/usr/src/app/main.js"]
#


# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

EXPOSE 8080
CMD [ "npm", "start" ]
